### PR TITLE
Add permissions check to staff view

### LINKED ISSUE #486: The loop staff page is accessible from the public view
## Expected behavior
User should be redirected to the "you don't have permission to view Loop" page when trying to view `www.lib.uchicago.edu/staff` publicly, if they haven't authenticated over Shibboleth.

## Actual behavior
Loop staff page at [www.lib.uchicago.edu/staff](https://www.lib.uchicago.edu/staff) is open for browsing by the public.

## Other information
Can be fixed by performing the same check we perform in `staff/views.py` to make sure the user is authenticated before viewing Loop search results.  Similar to how we resolved #391.

### PR DESCRIPTION
**Pull request by bufordrat**
Fixes #486.

**Changes in this request**
Add a simple check to staff/views.py to make sure user is authenticated before trying to view Loop staff page.  Follows same approach we used to deal with #391.

### CODE REVIEW

**Review by bbusenius — APPROVED** [review]
This is good. It looks like this file was never properly linted before so there's a fair amount of noise no matter what we do. I added a commit just to remove some unused imports and apply the auto-fixers. You'll want to get that change before you merge if you're doing it on the command line.

**Comment by bufordrat** [comment]
> This is good. It looks like this file was never properly linted before so there's a fair amount of noise no matter what we do. I added a commit just to remove some unused imports and apply the auto-fixers. You'll want to get that change before you merge if you're doing it on the command line.

Was my autofixer not working YET AGAIN????

**Comment by bufordrat** [comment]
> > This is good. It looks like this file was never properly linted before so there's a fair amount of noise no matter what we do. I added a commit just to remove some unused imports and apply the auto-fixers. You'll want to get that change before you merge if you're doing it on the command line.
> 
> Was my autofixer not working YET AGAIN????

I swear, it breaks every ten minutes!

**Comment by bbusenius** [comment]
I should have mentioned this on your last pull request. It looks like it is applying `autopep8` just fine but it's missing `isort` and `yapf`. That means your linter is fixing all the Pep8 errors but it's ignoring the code style suggestions.

**Pull request closed without merging**
