### PR TITLE
Search inputs are missing accessible text

### LINKED ISSUE #659: Search inputs are missing accessible text
## LIB20230113-06. Search inputs are missing accessible text (Blocker)
**Issue**: There are no labels on the Articles Plus and Website search inputs. These inputs do have aria-label="..." attributes, which do not convey the purpose of the inputs. The aria-labels on each input should be updated to provide meaningful accessible text/labeling for these inputs. 

## Related materials
[Full issue description](https://docs.google.com/document/d/15B0iu5qEQOI8BH-P48pgJul1-8A5b9d6Bi6PwoQvlTc/edit#heading=h.h09tizb0aqae)

### PR DESCRIPTION
**Pull request by bbusenius**
Fixes #659 

**Changes in this request**
- Replaces bad aria labels with meaningful text.
- Lints templates.

To view changes without linting whitespace differences, run this command when on the working branch:
```
git diff -w master
```

### CODE REVIEW

**Review by bufordrat — APPROVED** [review]
Lovely!  Nice to see some meaningful aria labels in there.

**Review by bluairis — COMMENTED** [review]
I might be wrong about this, because I am not quite sure why it is happening, but I was trying to test the aria labels by turning the voice over reader on, on my iMac. The interesting thing that I found is that the voice over does read the jourals search field differently when I am on wwwdev versus the current library website, however it doesn't work for the databases search tab or the articles search tab. In fact, it just reads them as search bars and doesn't describe them even though it does describe the journals search bars. Long story short, I am a bit confused why this is happening and I do not know if it is the aria label's fault exactly, but I thought it might be worth looking into.

**Comment by bbusenius** [comment]
@bluairis good catch! I'm not sure if I've fixed it but there's a good chance. I rearranged the html attributes on the inputs to match the one that was working and in doing so I found that the first one had an invalid second `id` attribute. That was definitely a problem. Please retest and let me know if it's better.

**Review by bluairis — APPROVED** [review]
Everything works! Looks great!

**Pull request merged**
