### PR TITLE
Unparsable structured data

### LINKED ISSUE #197: Unparsable structured data
## Problem
Google Search Console is sending the following report:
image
## Reason
This is a problem with `schema.org` on certain pages.
## Related materials
[More information from Google](https://www.google.com/appserve/mkt/p/AFnwnKXLcP2JeKLrED4hI34zh8OPdZyhcfYPufA3o7iFWY4mdnf2BEAxWW_-XgaiTQDunaWrNEqQIgszg0cvqi2jFDWnw6Afnj_mqk7MFqUvqZc8mQP9nrlMJx_BwPdzCwyRsD6_YQSNQP0LzTbH9NBEgj81ez-FdCPogOgX5R3n6sDLM6hXAnmLJ8kQEr6vRfFbKtTLnLCqsRG09e1HNpHow4A1FfjwBb60k2ud2WrcNp2yjxkYNWQGfUTbkBPCDC4Aw6fiT7bpp8iMplSCCenybcIRSn8kbtlwbQZzE-I2KhnbCmMnlLipX-Cpss4KthlkRyJGkZqvbUPCzxWg9Vr6VCSA3XeKPm7kKYRYILIDGykwl1LQIw)

### PR DESCRIPTION
**Pull request by bbusenius**
Fixes #197 

**Changes in this request**
- Added escapejs to schema.org fields.

### CODE REVIEW

**Comment by kzadrozny** [comment]
This looks good to go.

**Comment by bufordrat** [comment]
Cool!  Didn't know about template filters.  Big fan of pipelines, so that's right up my alley.

**Comment by kzadrozny** [comment]
Here is the article I spoke about that goes over the possible security issues with `escapejs`: https://alantrick.ca/writings/programming/django_escapejs_sec

**Comment by bufordrat** [comment]
Interesting; thanks!

**Pull request merged**
